export const CREATE_ACTION = "CREATE_ACTION"
export const UPDATE_ACTION = "UPDATE_ACTION"
export const DELETE_ACTION = "DELETE_ACTION"
export const LIST_ACTION = "LIST_ACTION"
export const DETAILS_ACTION = "DETAILS_ACTION"

